Repository sef-global/scholarx, pull requests merged in 2020-11, with the labels that each got.

#47 Add Mentor APIs with Unit tests
  src/main/java/org/sefglobal/scholarx/controller/MenteeController.java
  src/main/java/org/sefglobal/scholarx/controller/MentorController.java
  src/main/java/org/sefglobal/scholarx/controller/ProgramController.java
  src/main/java/org/sefglobal/scholarx/controller/admin/MenteeController.java
  src/main/java/org/sefglobal/scholarx/controller/admin/ProgramController.java
  src/main/java/org/sefglobal/scholarx/repository/MenteeRepository.java
  src/main/java/org/sefglobal/scholarx/repository/MentorRepository.java
  src/main/java/org/sefglobal/scholarx/service/MenteeService.java
  src/main/java/org/sefglobal/scholarx/service/MentorService.java
  src/main/java/org/sefglobal/scholarx/service/ProgramService.java
  src/main/java/org/sefglobal/scholarx/util/EnrolmentState.java
  src/main/java/org/sefglobal/scholarx/util/ProgramState.java
  src/test/java/org/sefglobal/scholarx/controller/MenteeControllerTest.java
  src/test/java/org/sefglobal/scholarx/controller/MentorControllerTest.java
  src/test/java/org/sefglobal/scholarx/controller/ProgramControllerTest.java
  src/test/java/org/sefglobal/scholarx/service/MenteeServiceTest.java
  src/test/java/org/sefglobal/scholarx/service/MentorServiceTest.java
  src/test/java/org/sefglobal/scholarx/service/ProgramServiceTest.java
Labels: enhancement

#66 Add mentee APIs with unit tests
  src/main/java/org/sefglobal/scholarx/controller/MentorController.java
  src/main/java/org/sefglobal/scholarx/controller/ProgramController.java
  src/main/java/org/sefglobal/scholarx/exception/NoContentException.java
  src/main/java/org/sefglobal/scholarx/repository/MenteeRepository.java
  src/main/java/org/sefglobal/scholarx/service/MentorService.java
  src/main/java/org/sefglobal/scholarx/service/ProgramService.java
  src/test/java/org/sefglobal/scholarx/controller/MentorControllerTest.java
  src/test/java/org/sefglobal/scholarx/controller/ProgramControllerTest.java
  src/test/java/org/sefglobal/scholarx/service/MentorServiceTest.java
  src/test/java/org/sefglobal/scholarx/service/ProgramServiceTest.java
Labels: enhancement

#71 Add missing common APIs with minor bug fixes
  src/main/java/org/sefglobal/scholarx/controller/MentorController.java
  src/main/java/org/sefglobal/scholarx/controller/ProgramController.java
  src/main/java/org/sefglobal/scholarx/service/MentorService.java
  src/main/java/org/sefglobal/scholarx/service/ProgramService.java
  src/main/resources/application.properties.example
  src/test/java/org/sefglobal/scholarx/controller/MentorControllerTest.java
  src/test/java/org/sefglobal/scholarx/controller/ProgramControllerTest.java
  src/test/java/org/sefglobal/scholarx/service/MentorServiceTest.java
  src/test/java/org/sefglobal/scholarx/service/ProgramServiceTest.java
Labels: enhancement

#77 Approving/Rejecting non PENDING mentors/mentees
  src/main/java/org/sefglobal/scholarx/service/MenteeService.java
Labels: Priority: Critical, enhancement

#73 Update user API to get the user's id from the session
  src/main/java/org/sefglobal/scholarx/controller/IntrospectionController.java
  src/main/java/org/sefglobal/scholarx/controller/MentorController.java
  src/main/java/org/sefglobal/scholarx/controller/ProgramController.java
  src/main/java/org/sefglobal/scholarx/controller/admin/ProgramController.java
  src/main/java/org/sefglobal/scholarx/exception/UnauthorizedException.java
  src/main/java/org/sefglobal/scholarx/repository/MenteeRepository.java
  src/main/java/org/sefglobal/scholarx/repository/MentorRepository.java
  src/main/java/org/sefglobal/scholarx/service/IntrospectionService.java
  src/test/java/org/sefglobal/scholarx/controller/IntrospectionControllerTest.java
  src/test/java/org/sefglobal/scholarx/controller/MentorControllerTest.java
  src/test/java/org/sefglobal/scholarx/controller/ProgramControllerTest.java
  src/test/java/org/sefglobal/scholarx/service/IntrospectionServiceTest.java
  src/test/java/org/sefglobal/scholarx/service/MenteeServiceTest.java
Labels: enhancement

#83 Update missed User endpoints: get profile id from a cookie
  src/main/java/org/sefglobal/scholarx/controller/MentorController.java
  src/main/java/org/sefglobal/scholarx/controller/ProgramController.java
  src/test/java/org/sefglobal/scholarx/controller/MentorControllerTest.java
  src/test/java/org/sefglobal/scholarx/controller/ProgramControllerTest.java
Labels: Priority: Critical

#85 Update two remaining endpoints to get JSON RequestBody
  src/main/java/org/sefglobal/scholarx/controller/MenteeController.java
  src/main/java/org/sefglobal/scholarx/controller/admin/MentorController.java
  src/main/java/org/sefglobal/scholarx/service/MenteeService.java
  src/test/java/org/sefglobal/scholarx/controller/MenteeControllerTest.java
  src/test/java/org/sefglobal/scholarx/controller/MentorControllerTest.java
Labels: enhancement

#88 Create user api to get a logged in user's mentees
  src/main/java/org/sefglobal/scholarx/controller/IntrospectionController.java
  src/main/java/org/sefglobal/scholarx/controller/admin/ProgramController.java
  src/main/java/org/sefglobal/scholarx/repository/MenteeRepository.java
  src/main/java/org/sefglobal/scholarx/service/IntrospectionService.java
  src/main/java/org/sefglobal/scholarx/service/ProgramService.java
  src/test/java/org/sefglobal/scholarx/controller/IntrospectionControllerTest.java
  src/test/java/org/sefglobal/scholarx/controller/ProgramControllerTest.java
  src/test/java/org/sefglobal/scholarx/service/IntrospectionServiceTest.java
  src/test/java/org/sefglobal/scholarx/service/ProgramServiceTest.java
Labels: Priority: Critical, enhancement

#90 Fix the logic in "get my mentees" endpoint
  src/main/java/org/sefglobal/scholarx/controller/IntrospectionController.java
  src/main/java/org/sefglobal/scholarx/repository/MenteeRepository.java
  src/main/java/org/sefglobal/scholarx/service/IntrospectionService.java
  src/test/java/org/sefglobal/scholarx/controller/IntrospectionControllerTest.java
  src/test/java/org/sefglobal/scholarx/service/IntrospectionServiceTest.java
Labels: Priority: Critical
